protein_mpnn:
  checkpoint_path: "MPNN_MODEL_WEIGHT"

usalign_path: "USALIGN_PATH"

known_sequence:
  sequence: "DIQVQVNIDDNGKNFDYTYTVTTESELQKVLNELMDYIKKQGAKRVRISITARTKKEAEKFAAILIKVFAELGYNDINVTFDGDTVTVEGQL"
  length: 92

target_structure:
  pdb_path: "data/1QYS.pdb"

experiment_config:
  generation: 500
  population: 20
  mpnn_temperature: 0.3
